#version 430
layout(local_size_x = 1, local_size_y = 1) in;

layout(std430, binding = 0) buffer lay0 { int inbuf[]; };
layout(std430, binding = 1) buffer lay1 { int outbuf[]; };

void main() {
	// drop threads outside the buffer dimensions.
	/* if(params.Width <= gl_GlobalInvocationID.x || params.Height <= gl_GlobalInvocationID.y){ */
	/* 	return; */
	/* } */
	const uint id = gl_GlobalInvocationID.x; // current offset

	outbuf[id] = inbuf[id] * inbuf[id];
}
